name: PR_checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-cache-${{ hashFiles('**/package-lock.json') }}

      - name: npm ci
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm ci

      - name: build
        run: npm run build --if-present

      - name: Keep build artefacts for later jobs
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/

      - name: linting
        run: npm run lint

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-cache-${{ hashFiles('**/package-lock.json') }}

      - name: unit tests
        run: npm run test:ci

  e2e_tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download build artefacts
        uses: actions/download-artifact@v1
        with:
          name: build

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-cache-${{ hashFiles('**/package-lock.json') }}

      - name: cypress
        run: npm run test:e2e

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: ./cypress/screenshots
  # lighthouse:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [10.x]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - uses: actions/cache@v1
  #       with:
  #         path: node_modules
  #         key: v1-cache-${{ hashFiles('**/package-lock.json') }}
  #     - name: run Lighthouse CI
  #       env:
  #         LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  #         REACT_APP_DEPLOYED_TO: production
  #         REACT_APP_AUTH_DOMAIN: tourlane.eu.auth0.com
  #         REACT_APP_AUTH_CLIENT_ID: phOFy5l3ZEv0ntBpa4x6PpMqpoA2yjJk
  #         REACT_APP_AUTH_AUDIENCE: https://kiwi.tourlane.com
  #         REACT_APP_GOOGLE_MAP_API_KEY: AIzaSyAIy4Paa44QA0130pL0Ulov2K-H0V7xmM0
  #         REACT_APP_KIWI_SEARCH_API: https://kiwi.tourlane.com/search/v1/items
  #         REACT_APP_KIWI_CONTENT_API: https://kiwi.tourlane.com/content
  #         REACT_APP_KIWI_SUPPLIERS_API: https://kiwi.tourlane.com/prices/dmcs.json
  #         REACT_APP_OSM_SEARCH_API: https://nominatim.openstreetmap.org
  #         REACT_APP_SENTRY_DSN: https://eab8e1b80d9e484b97466e71a7d4c15c@sentry.io/1511575
  #         REACT_APP_IMGIX_URL: https://tourlane-trips-assets-production.imgix.net
  #         GENERATE_SOURCEMAP: false
  #         REACT_APP_SHUTTERSTOCK_CLIENT: 165c4-effca-5cade-d4084-84714-ffdf1
  #         REACT_APP_SHUTTERSTOCK_SECRET: f5b72-22a0d-56b4d-1477d-bf062-6cb07
  #       run: |
  #         npm install -g @lhci/cli@0.3.x
  #         npm run lighthouse
  #         lhci upload
