name: PR_checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-cache-${{ hashFiles('**/package-lock.json') }}

      - name: npm ci
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm ci

      - name: build
        run: npm run build --if-present

      - name: Keep build artefacts for later jobs
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/

      - name: linting
        run: npm run lint

      - name: typescript
        run: npm run tsc

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-cache-${{ hashFiles('**/package-lock.json') }}

      - name: unit tests
        run: npm run test:ci

  e2e_tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download build artefacts
        uses: actions/download-artifact@v1
        with:
          name: build

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-cache-${{ hashFiles('**/package-lock.json') }}

      - name: cypress
        run: npm run test:e2e

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: ./cypress/screenshots
